using UnityEngine;

/// <summary>
/// Differential drive motor simulation.
///
/// Assumptions:
/// - RobotRoot follows Unity convention:
///     +Z = Forward
///     +Y = Up
///     +X = Right
///
/// - Visual model may be rotated internally.
/// - Forces are applied at wheel positions.
/// - Battery affects available torque.
/// - Motors have response time.
/// - No fake stabilization.
/// - No fake noise.
/// </summary>
public class SimulatedMotorDriver : MonoBehaviour
{
    // =====================================================
    // REFERENCES
    // =====================================================

    [Header("References")]

    public Rigidbody rb;

    public Transform leftWheelPoint;
    public Transform rightWheelPoint;

    // =====================================================
    // INPUTS
    // =====================================================

    [Header("Motor Inputs")]

    [Range(-1f, 1f)]
    public float leftInput;

    [Range(-1f, 1f)]
    public float rightInput;

    // =====================================================
    // BATTERY
    // =====================================================

    [Header("Battery")]

    [Range(0f, 1f)]
    public float currentBatteryCharge = 1f;

    // =====================================================
    // MOTOR MODEL
    // =====================================================

    [Header("Motor Model")]

    [Tooltip("Maximum force generated by each wheel.")]
    public float maxWheelForce = 0.25f;

    [Tooltip("How fast motors reach target command.")]
    public float motorResponseSpeed = 4f;

    [Tooltip("Resistance to sideways sliding.")]
    public float lateralGrip = 0.5f;

    // =====================================================
    // DEBUG
    // =====================================================

    [Header("Debug")]

    public bool drawDebug = true;

    // =====================================================
    // INTERNAL
    // =====================================================

    private float currentLeftMotor;
    private float currentRightMotor;

    // =====================================================
    // UNITY
    // =====================================================

    private void FixedUpdate()
    {
        // Debug.Log(
    // $"INPUTS  L={leftInput:F2} R={rightInput:F2}"
// );
        if (rb == null)
            return;

        UpdateMotorResponse();

        ApplyDriveForces();

        ApplyLateralGrip();
        // Debug.Log(
    // $"Velocity = {rb.velocity.magnitude:F4}"
// );
    }

    // =====================================================
    // MOTOR DYNAMICS
    // =====================================================

    private void UpdateMotorResponse()
    {
        currentLeftMotor = Mathf.MoveTowards(
            currentLeftMotor,
            leftInput,
            motorResponseSpeed * Time.fixedDeltaTime);

        currentRightMotor = Mathf.MoveTowards(
            currentRightMotor,
            rightInput,
            motorResponseSpeed * Time.fixedDeltaTime);
    }

    // =====================================================
    // DRIVE
    // =====================================================

    private void ApplyDriveForces()
    {

        float batteryFactor =
            Mathf.Clamp01(currentBatteryCharge);

        float leftForceMagnitude =
            currentLeftMotor *
            maxWheelForce *
            batteryFactor;

        float rightForceMagnitude =
            currentRightMotor *
            maxWheelForce *
            batteryFactor;

        Vector3 leftForce =
            leftWheelPoint.forward *
            leftForceMagnitude;

        Vector3 rightForce =
            rightWheelPoint.forward *
            rightForceMagnitude;

        rb.AddForceAtPosition(
            leftForce,
            leftWheelPoint.position,
            ForceMode.Force);

        rb.AddForceAtPosition(
            rightForce,
            rightWheelPoint.position,
            ForceMode.Force);

        if (drawDebug)
        {
            Debug.DrawRay(
                leftWheelPoint.position,
                leftWheelPoint.forward * 0.15f,
                Color.red);

            Debug.DrawRay(
                rightWheelPoint.position,
                rightWheelPoint.forward * 0.15f,
                Color.blue);
        }
        // Debug.Log(
    // $"Current Motors L={currentLeftMotor:F2} R={currentRightMotor:F2}"
// );

// Debug.Log(
//     $"Forces L={leftForceMagnitude:F2} R={rightForceMagnitude:F2}"
// );
    }

    // =====================================================
    // LATERAL GRIP
    // =====================================================

    private void ApplyLateralGrip()
    {
        ApplyWheelGrip(leftWheelPoint);

        ApplyWheelGrip(rightWheelPoint);
    }

private void ApplyWheelGrip(Transform wheel)
{
    Vector3 velocityAtWheel = rb.GetPointVelocity(wheel.position);

    // Corregido: Proyectamos sobre el eje derecho (lateral) de la rueda
    Vector3 lateralVelocity = Vector3.Project(velocityAtWheel, wheel.right);

    // La fuerza de corrección ahora sí frena el deslizamiento lateral (derrape)
    Vector3 correctionForce = -lateralVelocity * lateralGrip;

    rb.AddForceAtPosition(
        correctionForce,
        wheel.position,
        ForceMode.Force);

    if (drawDebug)
    {
        // Dibujamos el rayo hacia el lado para ver el vector de agarre lateral
        Debug.DrawRay(
            wheel.position,
            wheel.right * 0.10f,
            Color.green);
    }
}

    // =====================================================
    // PUBLIC API
    // =====================================================

    public void SetMotorInputs(
        float left,
        float right)
    {
        //Debug.Log($"SET MOTOR INPUTS L={left} R={right}");
        leftInput =
            Mathf.Clamp(left, -1f, 1f);

        rightInput =
            Mathf.Clamp(right, -1f, 1f);
    }

    public void Stop()
    {
        leftInput = 0f;
        rightInput = 0f;
    }
}